### ISSUE TITLE
[feature request] multi-lingual in one file (in-lining or embedding?)

### ISSUE THREAD

**Issue by paulvi** [takari/maven-polyglot#15]
Having many ways/language for doing the same may be attractive for some user groups, however it creates Babylon Tower problem when an example does not feat, because it was created for other language (sometimes with incompatible features).

Please consider way to incorporate e.g. XML parts into YAML or add YAML(groovy, scala, etc) into XML

**Comment by jvanzyl** [comment]
I honestly don't think this is a good idea.

**Comment by paulvi** [comment]
OK, the idea lives in maven-tiles https://github.com/repaint-io/maven-tiles

ref https://github.com/repaint-io/maven-tiles/issues/61
