### ISSUE TITLE
Provide a goal to generate pom.xml

### ISSUE THREAD

**Issue by jkubrynski** [takari/maven-polyglot#21]
If we could execute for example:
```
mvn io.takari.polyglot:polyglot-maven-plugin:generateXml
```
then projects using polyglot could be opened by any IDE supporting Maven. Of course it's just a walk-around, but it's still better than nothing.

**Comment by jvanzyl** [comment]
There's is a translation mechanism which I will try to get running and published in the form of a plugin today.

**Comment by jkubrynski** [comment]
That's cool! I was trying to run TeslaTranslatorCli directly from Maven using the exec plugin but there are some problems with missing dependencies.

**Comment by jvanzyl** [comment]
There is now a way to translate from one format to another generally but this takes care of translating pom.xml files to the new formats: http://takari.io/2015/03/21/polyglot-maven.html

**Comment by jvanzyl** [comment]
Everything should be in Maven Central so if you want to give it a try and let me know how it works I'd appreciate it. I notice that the elements don't come out in the nicest order in the translated POMs but it's a starting point.

**Comment by jkubrynski** [comment]
Thanks @jvanzyl - it works as a charm! Kudos for multi-project support and blazing fast reaction!
