### ISSUE TITLE
Scala DSL and cross building

### ISSUE THREAD

**Issue by ittaiz** [takari/maven-polyglot#23]
Hi,
I went over #22 and I wasn't sure if the Scala DSL is being cross built for 2.10/2.11
I think it's a really important requirement of most Scala users as it signals that the library will support them when a new version will come out (as well as for those not who haven't moved yet to 2.11)
Did I read it wrong?

**Comment by huntc** [comment]
Cross building is required as the plugin is executed on a different classpath to the project that you're building. I was able to demonstrate this with the example. Whereas the scala.pom is executed with Scala 2.10, the example project used Scala 2.11.

Incidentally the reason that the scala.pom is using 2.10 is because of a dependency on one of Twitter's library; the latter requiring 2.10.

Closing for now.

**Comment by ittaiz** [comment]
I saw that 2.11 and 2.10 were mentioned and didn't understand why since I
was looking only at the PR diff :-)
2 notes:
1. I'm pretty certain twitter util has a 2.11 version since we use twitter
util and are on 2.11, it did take them a long while to release it but it's
out. It's very likely the older version you were using was only 2.10.
2. We manage the whole Scala version by having a property called
scala.dependencies.version and all artifacts are defined
like twitter-util_${scala.dependencies.version}. Just a thought to group
the whole 2.10 literals and make upgrading easier.

‏בתאריך יום שני, 23 במרץ 2015, Christopher Hunt <notifications@github.com>
כתב:

**Comment by huntc** [comment]
I cannot locate twitter-eval for 2.11:

http://search.maven.org/#search%7Cga%7C1%7Ctwitter-util

Incidentally we're happy to accept PRs. :-)

**Comment by ittaiz** [comment]
You're right, I was sure everything moved.
I found this issue which seems to be the blocker
https://github.com/twitter/util/issues/105

With respect to the other change I mentioned would you like a PR with that?

‏בתאריך יום שני, 23 במרץ 2015, Christopher Hunt <notifications@github.com>
כתב:
