### ISSUE TITLE
What is "atom"?

### ISSUE THREAD

**Issue by jhftrifork** [takari/maven-polyglot#27]
I see a lot of common languages in the list of extensions here, with the exception of "atom". What is it? The syntax is unfamiliar, and the extension looks like it's self-contained.

**Comment by mosabua** [comment]
https://en.wikipedia.org/wiki/Atom_(standard)

**Comment by paulvi** [comment]
Also http://www.w3.org/2005/Atom
and http://tools.ietf.org/html/rfc4287

**Comment by huntc** [comment]
You've all got it wrong. :-)

[Dhanji Prassana](http://rethrick.com/#about) (ex Google) created Atom as an exploration of a similar build tool he used while at Google.

@dhanji Speak up. :-)

**Comment by jhftrifork** [comment]
The [sample `pom.atom`](https://github.com/takari/maven-polyglot/blob/master/poms/pom.atom) looks nothing like an Atom web feed; e.g., it's not XML.

**Comment by jvanzyl** [comment]
It's not, it is modeled on Blaze's syntax, or now the open sourced Bazel.io.

**Comment by mosabua** [comment]
Sorry... I got it all buggered up...

**Comment by dhanji** [comment]
The philosophy is to have a pure DSL specific to maven rather than a general purpose lang retro-fitted to maven.
